name: Pipeline CI/CD DataWeave CLI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-dataweave:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cod
        uses: actions/checkout@v4

      - name: Clone DataWeave CLI
        run: |
          git clone https://github.com/mulesoft/data-weave-cli.git "$HOME/dw-cli"

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: graalvm-community
          java-version: "21"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build DataWeave CLI
        run: |
          cd "$HOME/dw-cli"
          chmod +x gradlew
          ./gradlew native-cli:nativeCompile

      - name: Verify DataWeave CLI
        run: |
          DW="$HOME/dw-cli/native-cli/build/native/nativeCompile/dw"

          if [ ! -x "$DW" ]; then
            echo "ERROR: Executabilul dw nu a fost generat."
            echo "Fisiere generate:"
            find "$HOME/dw-cli/native-cli/build/native/nativeCompile" -maxdepth 2 -type f -print
            exit 1
          fi

          echo "dw găsit:"
          "$DW" --version

      - name: Add dw to PATH
        run: |
          echo "$HOME/dw-cli/native-cli/build/native/nativeCompile" >> "$GITHUB_PATH"

      - name: Test dw
        run: |
          which dw
          dw --version

      - name: Run DataWeave transformation
        run: |
          dw run -i payload="$GITHUB_WORKSPACE/input.json" "$GITHUB_WORKSPACE/transformare.dwl"
