name: Pipeline CI/CD DataWeave CLI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-dataweave:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codul tau din Git
        uses: actions/checkout@v4

      - name: Configurare Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache DataWeave Binary
        id: cache-dw
        uses: actions/cache@v4
        with:
          path: ~/dw-cli
          key: dw-cli-binary-v2

      - name: Clonare si Compilare DataWeave CLI (daca nu exista in cache)
        if: steps.cache-dw.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/mulesoft/data-weave-cli.git $HOME/dw-cli
          cd $HOME/dw-cli
          chmod +x gradlew
          ./gradlew native-cli:installDist -x test

      - name: Configurare PATH
        run: |
          DW_BIN_DIR=$(find $HOME/dw-cli/native-cli/build/install -type d -name "bin" | head -n 1)
          echo "$DW_BIN_DIR" >> $GITHUB_PATH

      - name: Executare si Validare Transformare DataWeave
        run: |
          dw --input payload input.json transformare.dwl