name: Pipeline CI/CD DataWeave CLI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-dataweave:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cod
        uses: actions/checkout@v4

      - name: Install DataWeave CLI
        shell: bash
        run: |
          set -e

          mkdir -p "$HOME/.dw"

          echo "Descarc DataWeave CLI 1.0.36..."

          curl -fL \
            "https://github.com/mulesoft/data-weave-cli/releases/download/v1.0.36/dw-1.0.36-Linux" \
            -o "$HOME/dw.zip"

          echo "Dezarhivez DataWeave CLI..."

          unzip -q "$HOME/dw.zip" -d "$HOME/.dw"

          echo "Continut ~/.dw:"
          find "$HOME/.dw" -maxdepth 2 -type f -print

          chmod +x "$HOME/.dw/bin/dw"

          echo "$HOME/.dw/bin" >> "$GITHUB_PATH"

      - name: Verify DataWeave CLI
        shell: bash
        run: |
          echo "Verific dw..."
          which dw
          dw --version

      - name: Run DataWeave transformation
        shell: bash
        run: |
          dw run \
            -i payload="$GITHUB_WORKSPACE/input.json" \
            "$GITHUB_WORKSPACE/transformare.dwl"
